### ISSUE TITLE
Test in AR datasets

### ISSUE THREAD

**Issue by Carinazhao22** [ygtxr1997/MSML#4]
Hello,

Thanks for sharing the codes! 
I am wondering how I can test the provided model in AR datasets. Thanks 

Carina

**Comment by ygtxr1997** [comment]
We do not provide AR dataset testing codes here because AR dataset has a very different data format (.mat), comparing with other commonly used evaluation benchmarks like LFW and MegaFace.
Besides, existing SOTA methods achive quite high testing scores on AR dataset, usually >100%.
The AR dataset is too small.
Therefore, we suggest using other larger occluded datasets like MFV, MFR2, LFW (add synthetic occlusions), and MegaFace (add synthetic occlusions) to evaluate the performance.
We are extending this work for larger benchmarks.
Smaller testing datasets will not be considered.
If you persist on using AR dataset, you may need to write testing codes by yourself.

**Comment by Carinazhao22** [comment]
I see, thank you!
