### ISSUE TITLE
About 'cvt_ms1m_masked.py'

### ISSUE THREAD

**Issue by a26z15** [ygtxr1997/MSML#8]
Thanks for sharing the codes! Could you please provide the 'cvt_ms1m_masked.py' with more details, thanks a lot!

**Comment by ygtxr1997** [comment]
We have some introduction about how to use mask augmentation in [https://github.com/ygtxr1997/MSML/tree/main/datasets#3-masked-face-dataset](https://github.com/ygtxr1997/MSML/tree/main/datasets#3-masked-face-dataset).
Dose this link help to solve your issue?

**Comment by a26z15** [comment]
There is no code in 'cvt_ms1m_masked.py'.
 Is the codes in 'cvt_ms1m_masked.py' basically the same as 'cvt_casia_webface_masked.py'? Except the size of the image?
Thanks for answering!

**Comment by ygtxr1997** [comment]
Using `cvt_casia_webface_masked.py` can also process the MS1M dataset.
You may just need to change the `root_folder` and make sure the `root_folder` contains `train.rec` and `train.idx` files.
Because our CASIA dataset and MS1M dataset were both downloaded from [https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_](https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_).
They have the same dataset format.

**Comment by a26z15** [comment]
I see. Thanks again！
